/* Une déclaration de struct qui utilise autres struct comme attributs */
struct testS {
    int a ;
    int b ;
    struct s1 *one, *two ;
};


/*  --> déclaration d'une fonction avec :
        paramètres : un pointeur sur une structure de type testS
        retourne : un pointeur sur une structure de type testS
*/
struct testS * structF(struct testS * ab) {
    ab->a = 1;
    while (i != 0) {
        a == b != c ;
    }
    return ab ;
}

