// if_else | or | while --> simple function
int mul(int a, int b) {
    if (a == 0 || b == 0) {
        return 0 ;
    }
    else {
        int res ;
        res = a ;
        int i ;
        i = 1 ;
        while (i != b) {
            res = res + a ;
            i = i+1 ;
        }
        return res ;
    }
}


int main() {

    int multi ;
    multi = mul(5,3) ;
    print(multi) ;

    return 0 ;
}