struct S1 {
    int a ;
};

// empty struct
struct S2 { } ;

struct S3 {
    int d,e ;
    struct S1 *one, *two ;
} ;

/*
    - param : struct
    - return : struct
    - "->"
*/
struct S1 * struct_function(struct S1 * abc) {
    abc->a = 1;
    return abc ;
}


int main() {

    struct S1 *abc1 ;
    abc1 = malloc(sizeof(struct S1)) ;  //malloc, sizeof
    abc1 = struct_function(abc1);
    print(abc1->a) ;

    return 0 ;
}