// simple function with "+"
int sum(int a1, int a2){
    int S ;
    S = a1 + a2 ;
    return S ;
}

// op's priority (function without param)
int calculate() {
    int res;
    res = 1 + 10 * 2 - 40 + (10 - 2) / 2 ;
    return res ;
}


int main() {

    // Using a new var to print result
    int S ;
    S = sum(3,2) ;
    print(S) ;

    // Print the result without using a new var
    print(calculate()) ;

    return 0 ;
}